### ISSUE TITLE
Assembly load from network location

### ISSUE THREAD

**Issue by Zoryn4163** [Zoryn4163/SMAPI#6]
[19:31:17] Game failed to start: System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at StardewModdingAPI.Program.LoadMods()
   at StardewModdingAPI.Program.RunGame()

On version 0.3, where the issue should not persist.

**Comment by HandsomeMatt** [comment]
#4 didn't fix this?

**Comment by yuukiw** [comment]
no it isnt fixed

**Comment by HandsomeMatt** [comment]
I'll run an AppDomain in the refactor then.

**Comment by Zoryn4163** [comment]
I can't seem to sleep :l
I can do 'Assembly mod = Assembly.UnsafeLoadFrom(s);' if we don't want to bother - it just skips the security checks.

**Comment by Zoryn4163** [comment]
38bce3315841c66409e02844c86eb7a5e9295565 should fix this with an unsafe load call because who cares about security?
